document.write('<!DOCTYPE html>');
document.write('<html lang="en" >');
document.write('<head>');
document.write('  <meta charset="UTF-8">');
document.write('  <title>Kavidu Dilhara</title>');
document.write('  <link href="https://fonts.googleapis.com/css?family=Delius+Swash+Caps" rel="stylesheet"><link rel="stylesheet" href="css/kitty.min.style.css">');
document.write('  <link rel="icon" type="image/x-icon" href="img/favicon.ico">');
document.write('');
document.write('</head>');
document.write('<body>');
document.write('<!-- partial:index.partial.html -->');
document.write('<div class="wrapper-no7">');
document.write('    <div class="logo"></div>');
document.write('    <div class="animation-wrapper">');
document.write('        <div class="cat-wrapper">');
document.write('            <svg class="cat" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 207.68 163.77" preserveAspectRatio="none">');
document.write('              <title>cat</title>');
document.write('              <g class="body">');
document.write('                <circle class="body-backcircle" cx="76.86" cy="83.31" r="45.5"/>');
document.write('                <circle class="body-frontcircle" cx="150.86" cy="83.31" r="45.5"/>');
document.write('                <rect class="body-between"x="74.65" y="37.89" width="83.04" height="90.61"/>');
document.write('              </g>');
document.write('              <circle class="head" cx="161.76" cy="52.75" r="45.92"/>');
document.write('              <g class="eyes">');
document.write('                <circle class="eyes-l" cx="153.51" cy="46.5" r="8.25"/>');
document.write('                <circle class="eyes-r" cx="185.76" cy="46.5" r="8.25"/>');
document.write('              </g>');
document.write('              <g class="ears">');
document.write('                <polygon class="ears-l" points="132.76 19 132.76 0 149.55 8.81 132.76 19"/>');
document.write('                <polygon class="ears-r" points="179.44 11.2 197 4.06 195.16 22.9 179.44 11.2"/>');
document.write('              </g>');
document.write('              <rect class="tail" x="-11" y="32.87" width="107" height="20" rx="9.58" ry="9.58" transform="translate(41.19 -18.41) rotate(45)"/>');
document.write('              <g class="backlegs">');
document.write('                <path class="backlegs1" d="M74,124.85a6,6,0,0,0-4.7-7.07l-4.41-.89a6,6,0,0,0-7.07,4.7l-6.31,31.35a8.25,8.25,0,1,0,15.64,5,5.94,5.94,0,0,0,.44-1.33Z" transform="translate(-1.58 -0.92)"/>');
document.write('                <path class="backlegs2" d="M88.22,125.86a6,6,0,0,0-4.38-7.27l-4.37-1.08a6,6,0,0,0-7.27,4.38l-7.69,31a8.25,8.25,0,1,0,15.41,5.72,5.94,5.94,0,0,0,.5-1.31Z" transform="translate(-1.58 -0.92)"/>');
document.write('              </g>');
document.write('              <g class="frontlegs">');
document.write('                <path class="frontlegs1" d="M162.89,120.91a6,6,0,0,0-7.65-3.68L151,118.72a6,6,0,0,0-3.68,7.65l10.57,30.18a8.25,8.25,0,1,0,16-3.65,5.94,5.94,0,0,0-.3-1.37Z" transform="translate(-1.58 -0.92)"/>');
document.write('                <path class="frontlegs2" d="M175.77,120.08a6,6,0,0,0-7.48-4l-4.31,1.3a6,6,0,0,0-4,7.48l9.22,30.62a8.25,8.25,0,1,0,16.17-2.94,5.94,5.94,0,0,0-.24-1.38Z" transform="translate(-1.58 -0.92)"/>');
document.write('              </g>');
document.write('            </svg>');
document.write('        </div>');
document.write('        <div class="logoani">Loading...</div>');
document.write('    </div>');
document.write('    <div class="layout notvisible">');
document.write('<div>');
document.write('');
document.write('');
document.write('<!-- code by Kavidu-Dilhara -->');
document.write('<!-- start in about section -->');
document.write('<!DOCTYPE html>');
document.write('<html lang="en">');
document.write('<head>');
document.write('    <meta charset="UTF-8">');
document.write('    <meta http-equiv="X-UA-Compatible" content="IE=edge">');
document.write('    <meta name="viewport" content="width=device-width, initial-scale=1.0">');
document.write('    <title>Kavidu Dilhara</title>');
document.write('    <link rel="stylesheet" href="css/style.css">');
document.write('</head>');
document.write('<body>');
document.write('<!-- Messenger Chat Plugin Code -->');
document.write('    <div id="fb-root"></div>');
document.write('');
document.write('    <!-- Your Chat Plugin code -->');
document.write('    <div id="fb-customer-chat" class="fb-customerchat">');
document.write('    </div>');
document.write('');
document.write('    <script>');
document.write('      var chatbox = document.getElementById(\'fb-customer-chat\');');
document.write('      chatbox.setAttribute("page_id", "103280425760120");');
document.write('      chatbox.setAttribute("attribution", "biz_inbox");');
document.write('    </script>');
document.write('');
document.write('    <!-- Your SDK code -->');
document.write('    <script>');
document.write('      window.fbAsyncInit = function() {');
document.write('        FB.init({');
document.write('          xfbml            : true,');
document.write('          version          : \'v14.0\'');
document.write('        });');
document.write('      };');
document.write('');
document.write('      (function(d, s, id) {');
document.write('        var js, fjs = d.getElementsByTagName(s)[0];');
document.write('        if (d.getElementById(id)) return;');
document.write('        js = d.createElement(s); js.id = id;');
document.write('        js.src = \'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js\';');
document.write('        fjs.parentNode.insertBefore(js, fjs);');
document.write('      }(document, \'script\', \'facebook-jssdk\'));');
document.write('    </script>');
document.write('    <div class="card" data-state="#about">');
document.write('       <div class="card-header">');
document.write('           <div class="card-cover" style="background-image: url(img/kavidu.crypt);"></div>');
document.write('           <img src="img/kavidu.crypt" alt="Avatar" class="card-avatar">');
document.write('           <h1 class="card-fullname">Kavidu Dilhara</h1>');
document.write('           <h2 class="card-jobtitle">Front-End Web Developer & Designer</h2>');
document.write('       </div>');
document.write('       <div class="card-main">');
document.write('           <div class="card-section is-active" id="about">');
document.write('               <div class="card-content">');
document.write('                   <div class="card-subtitle">ABOUT</div>');
document.write('                   <p class="card-desc">Hi there! I\'m a Just a simple person and Web Designer.I\'m still a student and currently studying languages ​​like<u> Javascript,HTML,CSS,PHP.</u></p>');
document.write('                  ');
document.write('               </div>');
document.write('               <div class="card-social">');
document.write('                   <a href="https://www.facebook.com/kavidu.dilhara.0"><img src="./img/facebook.png" alt="Facebook"></a>');
document.write('                   <a href="https://github.com/kavidu-dilhara"><img src="./img/github.png" alt="Twitter"></a>');
document.write('                   <a href="https://wa.me/qr/6YU2FJRVFLGAM1"><img src="./img/whatsapp.png" alt="Insta"></a>');
document.write('                   <a href="https://www.linkedin.com/in/kavidu-dilhara"><img src="./img/linkedin.png" alt="Linkedin"></a>');
document.write('                     <a href="https://www.instagram.com/kavidudilhara_"><img src="./img/instagram.png" alt="intragram"></a>');
document.write('                       <a href="https://codepen.io/kavidudilhara"><img src="./img/codepen.png" alt="codepen"></a>');
document.write('                         <a href="https://www.pinterest.com/kavidudilhara_/"><img src="./img/pinterest.png" alt="pinterest"></a>');
document.write('               </div>');
document.write('           </div>');
document.write('           <!-- end  in about section -->');
document.write('           <!-- start in timeline section -->');
document.write('           <div class="card-section" id="experience">');
document.write('               <div class="card-content">');
document.write('                   <div class="card-subtitle">My Time Line</div>');
document.write('                   <div class="card-timeline">');
document.write('                       ');
document.write('                        <div class="card-item" data-year="2022">');
document.write('');
document.write('<!-- Time line item 0 -->');
document.write('');
document.write('                           <div class="card-item-title">Nothing important to mention. <span>The timeline is moving🕕</span></div>');
document.write('');
document.write('                           <div class="card-item-desc">            <script>');
document.write('');
document.write('function display_ct5() {');
document.write('var x = new Date()');
document.write('var ampm = x.getHours( ) >= 12 ? \' PM\' : \' AM\';');
document.write('');
document.write('var x1=x.getMonth() + 1+ "/" + x.getDate() + "/" + x.getFullYear(); ');
document.write('x1 = x1 + " - " +  x.getHours( )+ ":" +  x.getMinutes() + ":" +  x.getSeconds() + ":" + ampm;');
document.write('document.getElementById(\'ct5\').innerHTML = x1;');
document.write('display_c5();');
document.write(' }');
document.write(' function display_c5(){');
document.write('var refresh=1000; // Refresh rate in milli seconds');
document.write('mytime=setTimeout(\'display_ct5()\',refresh)');
document.write('}');
document.write('display_c5()');
document.write('</script>');
document.write('<span id=\'ct5\'></span></div>');
document.write('                       </div>  ');
document.write('                           <div class="card-item" data-year="2021">');
document.write('                        <div class="card-item-title">Start the work with Github <span>💬</span></div>');
document.write('                        <div class="card-item-desc">My Github profile on the about section.</div>');
document.write('                    </div>');
document.write('                        <div class="card-item" data-year="2021">');
document.write('');
document.write('                           <div class="card-item-title">Start a new school life in a new school <span>🧑‍🎓</span></div>');
document.write('');
document.write('                           <div class="card-item-desc">I think this will be an unforgettable time.</div>');
document.write('                       </div>');
document.write('                                 <div class="card-item" data-year="2020">');
document.write('');
document.write('                           <div class="card-item-title">Start learning UI / UX development <span>💻</span></div>');
document.write('');
document.write('                           <div class="card-item-desc">It helped to make the great web design.</div>');
document.write('                       </div>');
document.write('                            <div class="card-item" data-year="2020">');
document.write('');
document.write('                           <div class="card-item-title">The love story stopped <span>&#x1F494</span></div>');
document.write('');
document.write('                           <div class="card-item-desc">That\'s good. I learned a lot from it.😊</div>');
document.write('                       </div>');
document.write('                            <div class="card-item" data-year="2019">');
document.write('');
document.write('                           <div class="card-item-title">I faced G.C.E. (O/L) EXAMINATION <span>🤷</span></div>');
document.write('');
document.write('                           <div class="card-item-desc">Easy, it passed too</div>');
document.write('                       </div>');
document.write('                              <div class="card-item" data-year="2019">');
document.write('');
document.write('                           <div class="card-item-title">Started learning HTML and CSS. <span>🖥️</span></div>');
document.write('');
document.write('                           <div class="card-item-desc">I started learning HyperText Markup Language and Cascading Style Sheets because of my passion for web design.</div>');
document.write('                       </div>');
document.write('                    ');
document.write('');
document.write('                       <div class="card-item" data-year="2013">');
document.write('                           <div class="card-item-title">I faced grade 5 scholarship exam <span>🙆‍♂️</span></div>');
document.write('                           <div class="card-item-desc">It just passed(Mothers\' Exam🤣).</div>');
document.write('                       </div> ');
document.write('                  <div class="card-item" data-year="2009">');
document.write('');
document.write('                           <div class="card-item-title">The year I started going to school. <span>👨‍🎓</span></div>');
document.write('');
document.write('                           <div class="card-item-desc">I was a little kid then.</div>');
document.write('                       </div>');
document.write('                     <div class="card-item" data-year="2003">');
document.write('');
document.write('                           <div class="card-item-title">This is the year I was born. <span>😊</span></div>');
document.write('');
document.write('                           <div class="card-item-desc">I was born after 2000😁</div>');
document.write('                       </div>');
document.write('                ');
document.write('                   </div>');
document.write('               </div>');
document.write('           </div>');
document.write('           <!-- end in timeline section -->');
document.write('           ');
document.write('           <!-- start in contact section -->');
document.write('           <div class="card-section" id="contact">');
document.write('               <div class="card-content">');
document.write('                   <div class="card-subtitle">Contact</div>');
document.write('                   <div class="card-contact-wrapper">');
document.write('                       <div class="card-contact">');
document.write('                           <img src="img/location.png" alt="Location">');
document.write('                           Plus code=<a href="');
document.write('https://maps.app.goo.gl/sbrVH9mqrNoFBDqHA">8HMH+RQW Weranketagoda</a>');
document.write('                       </div>');
document.write('                    <div class="card-contact">');
document.write('                        <img src="img/phone.png" alt="Phone">');
document.write('                        +94 75 43 42 061');
document.write('                    </div>');
document.write('                    <div class="card-contact">');
document.write('                        <img src="img/mail.png" alt="Email">');
document.write('                              <a href="mailto:Contact@kavindudilhara.tk?subject=kavindu%20dilhara%20-%20contact&body=Compose%20your%20email">Contact@kavindudilhara.tk</a>');
document.write('                    </div> ');
document.write('                    <button class="myblog"onclick="window.location.href=\'https://blog.kavidudilhara.ml\';">My Blog</button>');
document.write('                   </div>');
document.write('               </div>');
document.write('           </div>');
document.write('           <div class="card-buttons">');
document.write('               <button class="is-active" data-section="#about">ABOUT</button>');
document.write('               <button  data-section="#experience">Time Line</button>');
document.write('               <button  data-section="#contact">CONTACT</button>');
document.write('           </div>');
document.write('       </div>');
document.write('    </div>');
document.write('    <!-- end in contact  section -->');
document.write('    <script language=JavaScript>');
document.write('	');
document.write('	//Disable right mouse click Script');
document.write('');
document.write('	');
document.write('	');
document.write('	var message="❗ Right Mouse click is disabled!";');
document.write('	');
document.write('	///////////////////////////////////');
document.write('	function clickIE4(){');
document.write('	if (event.button==2){');
document.write('	alert(message);');
document.write('	return false;');
document.write('	}');
document.write('	}');
document.write('	');
document.write('	function clickNS4(e){');
document.write('	if (document.layers||document.getElementById&&!document.all){');
document.write('	if (e.which==2||e.which==3){');
document.write('	alert(message);');
document.write('	return false;');
document.write('	}');
document.write('	}');
document.write('	}');
document.write('	');
document.write('	if (document.layers){');
document.write('	document.captureEvents(Event.MOUSEDOWN);');
document.write('	document.onmousedown=clickNS4;');
document.write('	}');
document.write('	else if (document.all&&!document.getElementById){');
document.write('	document.onmousedown=clickIE4;');
document.write('	}');
document.write('	');
document.write('	document.oncontextmenu=new Function("alert(message);return false")');
document.write('	');
document.write('	</script>');
document.write('<script src="js/script.js"></script>    ');
document.write('</body>');
document.write('</html>');
document.write('</script>');
document.write('</script>');
document.write('</div>');
document.write('');
document.write('<br>');
document.write('');
document.write(' <img src="img/1.gif" alt="Girl in a jacket" width="350" height="200">');
document.write('    </div>');
document.write('    <button class="restart"></button>');
document.write('   ');
document.write(' </div>');
document.write('<!-- partial -->');
document.write('  <script src=\'https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.2/TweenMax.min.js\'></script><script  src="js/kitty.min.script.js"></script>');
document.write('');
document.write('</body>');
document.write('</html>');
document.write('');